@include('Pages.header')
        @include('Pages.Banner')
        @include('Pages.About')
        @include('Pages.Benifits')
        @include('Pages.Services')
        @include('Pages.Updates')
        @include('Pages.News')
@include('Pages.footer')